### PR TITLE
Convert layout to tables

### PR DESCRIPTION
**Pull request by Decagon**
Converted the layout to a tabular one. Let me know if you see any errors as I just quickly reviewed it.

I'll be able to fix anything later today

### CODE REVIEW

**Comment by Tunous** [comment]
1. `See Tables/Badges` notes aren't displayed in "add" message (and most likely other too). Just add them italicized to the description column. In other messages they sometimes have unnecessary > sign.

2. "allowSpectating", "joinCampaign", "m" (both send and receive), "reset", "show", "pressKey" are broken.

3. Notes for messages such as "completedLevel", "editRgiths" aren't displayed on new line. Trailing white-spaces were here so they land on new-lines.

4. I don't really like how 3rd columns are named **Event**. **Name** seems much more fitting here since they are names of message parameters.

5. In "init" receive message serialized world data and *we* shouldn't have id. Use `[...]` (or just `...`) here.

That's all I found but there still might be something I missed.

**Comment by Decagon** [comment]
I'll squash these commits tomorrow; should have fixed everything except I broke most of the tables now (and I'll have to fix that soon.)

**Comment by Decagon** [comment]
Should have fixed everything; let me know if there's anything else that I missed (there were a few indexes that were off that were fixed too.)

**Comment by Tunous** [comment]
Thanks

**Pull request merged**
